### ISSUE TITLE
Error on layer without feature IDs

### ISSUE THREAD

**Issue by pnorman** [terranodo/tegola#126]
I have a layer without feature IDs. When I give it the definition
```toml
[[providers.layers]]
  name = "ocean"
  geometry_fieldname = "way"
  sql = "SELECT ST_AsBinary(way) AS way FROM ne_ocean WHERE way && !BBOX!"
```

I get the error `2017/05/31 12:12:49 SQL for layer(0) ocean does not contain the id field for the geometry: gid`

There is no field for this table that could be used as an ID.
