### ISSUE TITLE
No point being displayed?

### ISSUE THREAD

**Issue by bagage** [terranodo/tegola#128]
For lowest zoom I'm trying to display points instead of polygons to avoid overloading the map; however I fail to display any of them. I am using the following query: `sql = "SELECT ST_AsBinary(ST_Centroid(way)) AS way, osm_id FROM planet_osm_polygon WHERE way && !BBOX!"`. Removing the `ST_Centroid()` "solves" the problem, eg. polygons are properly displayed.

I am not sure if the issue is on server side or client side but:

- Leaflet vectorgrid [demo points works](https://raw.githubusercontent.com/Leaflet/Leaflet.VectorGrid/master/docs/demo-points.html) with their URL
- If I change URL with mine, no points are displayed. That's the **only change I made on client side**
- But in the mean time, the server seems to return some results:

```
2017/06/09 13:57:57 Got 6 rows running:
SELECT ST_AsBinary(way) AS way, osm_id FROM planet_osm_polygon WHERE way && ST_MakeEnvelope(9.250488279962338,41.38505194495075,9.261474608085809,41.37680856094684,4326)
Did complete true
```

Full config:

```toml
[webserver]
port = ":8080"

[[providers]]
name = "test"
type = "postgis"
host = "172.17.0.1"
port = 25432
database = "gis"
user = "docker"
password = "docker"
srid = 4326

[[providers.layers]]
  name = "cities-point"
  geometry_fieldname = "way"
  id_fieldname = "osm_id"
  # sql = "SELECT ST_AsBinary(ST_SimplifyPreserveTopology(way,1)) AS way, name, osm_id FROM planet_osm_polygon WHERE way && !BBOX!"
  sql = "SELECT ST_AsBinary(ST_Centroid(way)) AS way, name, osm_id FROM planet_osm_polygon WHERE way && !BBOX!"
  # sql = "SELECT ST_AsBinary(ST_PointN(ST_Exteriorring(way), 1)) AS way, name, osm_id FROM planet_osm_polygon WHERE way && !BBOX!"

[[maps]]
name = "zoning"

  [[maps.layers]]
  provider_layer = "test.cities-point"
  min_zoom = 1
  max_zoom = 10
```

Any help appreciated :). Running tegola from docker `terranodo/tegola`.
