### ISSUE TITLE
Missing holes from polygons

### ISSUE THREAD

**Issue by pnorman** [terranodo/tegola#150]
With the configuration

```toml
[webserver]
port = ":9090"

[[providers]]
name = "vector_demo"	# provider name is referenced from map layers
type = "postgis"		# the type of data provider. currently only supports postgis
host = "/var/run/postgresql"		# postgis database host
port = 5432				# postgis database port
database = "osmcarto_bc" 	# postgis database name
user = "pnorman"
password = ""

  [[providers.layers]]
  name = "water-lz"
  geometry_fieldname = "way"
  id_fieldname = "osm_id"
  sql = """
  SELECT
      0 AS osm_id,
      ST_AsBinary(way) AS way,
      'ocean' AS water
    FROM ne_ocean
    WHERE way && !BBOX!
  UNION ALL
  SELECT
      0 AS osm_id,
      ST_AsBinary(way) AS way,
      'lake' AS water
    FROM ne_lake
    WHERE way && !BBOX!
  """

[[maps]]
name = "vector_demo"
[[maps.layers]]
provider_layer = "vector_demo.water-lz"
min_zoom = 0
max_zoom = 5
```

I get

![image](https://user-images.githubusercontent.com/1190866/30891514-a499e652-a2e8-11e7-9ace-93437a15a456.png)

The problem is the missing Americas.

Not being sure if this was a problem with the qgis vector tile plugin, I downloaded the 2/0/1 tile and converted it to geojson with vt2geojson. I got the same problem.
