### ISSUE TITLE
PostGIS: hstore tags should not override column tags

### ISSUE THREAD

**Issue by ARolek** [terranodo/tegola#154]
Example config:

```toml
# Buildings
[[providers.layers]]
name = "buildings"
geometry_fieldname = "geometry"
id_fieldname = "osm_id"
sql = "SELECT ST_AsBinary(geometry) AS geometry, osm_id, name, nullif(as_numeric(height),-1) AS height, type, tags FROM osm_buildings WHERE geometry && !BBOX!"
```

In the above example there is a height property as a column and a heigh property in the `tags` hstore. The `tags` heigh value is overwriting the `height` column. hstore values should not overwrite values that already exist.
