### ISSUE TITLE
Config file format

### ISSUE THREAD

**Issue by ARolek** [terranodo/tegola#21]
We need to figure out a config file format which will support the following:

- [ ] Data providers
  - [x] PostGIS
      - [x] Layer definitions and associated SQL
      - [x] Zoom level
- [ ] web server
  - [x] port
  - [x] max zoom? - 18 is suggested by slippy maps spec. 
  - [ ] max tile size? - currently throws a warining with tile > 500k

**Comment by ingenieroariel** [comment]
It would be very interesting to try to mimic mapproxy's config file when
possible: http://mapproxy.org/docs/nightly/configuration.html

It's yaml based and already has provisions for things like grid set, source
types, zoom levels, transparency, etc.

**Comment by ARolek** [comment]
@ingenieroariel thanks for the reference. That's going to be very helpful. One of the issues I'm trying to figure out is how we want to deal with user defined SQL queries at various zoom levels when leveraging PostGIS. At first glance I don't see mapproxy working with PostGIS but I might have missed it. 

Any ideas?

**Comment by ingenieroariel** [comment]
Yeah - that's a very interesting point that I think mapproxy does not answer. Maybe it's worth looking at what CartoDB SQL API does (although that one is for http):

https://docs.cartodb.com/cartodb-platform/sql-api/making-calls/

**Comment by ARolek** [comment]
It appears they're passing SQL through a query string which I don't think is an approach we should take. I would rather the user predefine the SQL at config time. 

I'm going to dig into mapproxy's config file a bit more as it seems pretty robust. My main internal battle with the config file is figuring out how to handle SQL statements. Once we have a direction on that we should be able to stub out a first version.

**Comment by ARolek** [comment]
mapnik uses an XML file for config and use SQL inline with a !bbox! param that is replaced at query time. They also expect a table to have a `gid` column as the feature unique id. More details [here](https://github.com/mapnik/mapnik/wiki/PostGIS)

**Comment by gdey** [comment]
Current thinking for the YAML file:
```yaml
---
data_provider:                                               # Map of providers, the key is the provider name.
    "provider1":
         connection_string: "localhost:8080…" # This is the connection string
         type: "postgis"                                      # The provider type
map_ids:                                                       # Map of map ids, the key is the map id name.
     "topo":               
         - "layer1"                                              # List of layers in the map, each map must have at least one layer.
layers:                                                           # Map of the layers in the system, the key is the layer name.
    "layer1":
        data_provider: "provider1"                    # Which data_provider the layers uses.
        config: "…"                                            # The config for the layer.
```

**Comment by jj0hns0n** [comment]
Can we add some basic docs on the format now that its working?

**Comment by ARolek** [comment]
config format is evolving to. here's the new draft

```toml
[webserver]
port = ":8080"

# register data providers
[[providers]]
name = "test_postgis"
type = "postgis"
host = "localhost"
port = 5432
database = "ARolek" 
user = "ARolek"
password = ""

	[[providers.queries]]
	name = "landuse" 				# will be encoded as the layer name in the tile
	sql = "gis.zoning_base_3857" 	# sql or table_name are required
	table_name = "foo" 			
	geom_field = "geom"				# geom field. default is geom
	gid_field = "gid"				# geom id field. default is gid

  	[[providers.queries]]
	name = "landuse1"
	sql = "SELECT ST_AsBinary(wkb_geometry) AS wkb_geometry, name, ogc_fid FROM buildings_mercator WHERE wkb_geometry && {{.BBox}}"

# maps are made up of layers
[[maps]]
name = "zoning"					# used in the URL to reference this map

	[[map.layers]]
	name = "landuse"
	provider = "test_postgis.landuse"	#	points to a proivder.queries name
	minzoom = 12
	maxzoom = 16
```
