### ISSUE TITLE
error fetching geometry type for layer

### ISSUE THREAD

**Issue by pnorman** [terranodo/tegola#320]
With this config I get an error

```toml
[webserver]

[[providers]]
name = "osm2pgsql"
type = "postgis"
host = "/var/run/postgresql" # Default for Debian-based distributions
port = 5432                     # postgis database port
database = "gis"        # postgis database name
user = "pnorman"
password = ""

  [[providers.layers]]
  name = "water"
  id_fieldname = "osm_id"
  geometry_fieldname = "way"
  sql = """
  SELECT
      0::bigint AS osm_id,
      ST_AsBinary(way) AS way
    FROM ne_ocean
    WHERE way && !BBOX!
  UNION ALL
  SELECT
      0::bigint AS osm_id,
      ST_AsBinary(way) AS way
    FROM ne_lake
    WHERE way && !BBOX!
  """

[[maps]]
name = "bolder"

[[maps.layers]]
provider_layer = "osm2pgsql.water"
min_zoom = 0
max_zoom = 5
```

```
$ SQL_DEBUG=EXECUTE_SQL ./tegola_linux_amd64 serve
2018/02/22 17:02:44 config.go:161: Loading local config (config.toml)
2018/02/22 17:02:44 root.go:75: error fetching geometry type for layer (water): ERROR: UNION types text and bytea cannot be matched (SQLSTATE 42804)
```
