### ISSUE TITLE
hstore support in postgis provider

### ISSUE THREAD

**Issue by ARolek** [terranodo/tegola#71]
When working with an OSM export translated using osmosis some key / val pairs are being stored in an `hstore` datatype in PostGIS. These values are currently being encoded as a single string. We should decode the hstore and add the values alongside the feature's other tags.

**Comment by ARolek** [comment]
@gdey do you recall why we have [this block of code](https://github.com/terranodo/tegola/blob/issue-71/provider/postgis/postgis.go#L484)? While implementing hstore support this line is causing a bug where the tag is being encoded but is empty. A couple things to note: 

- Hstore's are key value pairs, and I'm simply adding all of the k/v pairs in the hstore to the feature tags, but the original hstore column that was referenced is empty. This is kind of obscure behavior. For example, OSM dumps have a column called "other_tags" which is an hstore. Once I encode all the k/v pairs in the "other_tags" column, the aforementioned block still encodes an empty "other_tags" tag in the feature.
- Since we support a "fields" array in our config and filter columns by that array, if the user references an hstore should we encode everything in the hstore? Alternatively we could look for hstores, decode them and sniff for values in them per the provided "fields" array. I'm leaning towards the former.

**Comment by ARolek** [comment]
While testing the hstore implementation it appears that all hstore values are of type string. This may cause problems when trying to use values for say "building_height" to extrude buildings. I think trying to parse every string into a float / int would be unnecessary overhead. An alternative solution is to allow the user to configure how to handle an hstore field. This would also allow for filtering out unnecessary values. A possible config:

```toml
[[providers]]
name = "bonn_osm"
type = "postgis"
host = ""
port = 5432
database = "" 
user = ""
password = ""

    [[providers.layers]]
    name = "building"
    tablename = "buildings_3857"
    geometry_fieldname = "wkb_geometry"
    id_fieldname = "ogc_fid"
    fields = [ "name", "amenity", "shop", "other_tags"]

		[[providers.layers.other_tags]]
		fields = [ "name", "amenity", "shop", "other_tags"] # field filter

			[[providers.layers.other_tags.building_height]]
			name = "foo" # for mapping the name to another value?
			data_type = "int32" # datatype to parse. this needs to be thought out more.
			default = 0 # default value if the parsing fails. is this necessary?

```
