### ISSUE TITLE
When using two providers if the same layer name exists across providers we need to alert the user.

### ISSUE THREAD

**Issue by ARolek** [terranodo/tegola#81]
Currently a config like the following will stop rendering in OpenLayers v3 after it hits the second `water` layer. All subsequently configured layers will not show up. This is only an issue if we have two providers configured with the same layer name and they're both set to render at a certain zoom.

Notice we have two different providers, each with a layer named `water`. The MVT spec requires unique layer names. 

``` toml
[[providers]]
name = "provider1"
type = "postgis"
host = "localhost"
port = 5432
database = "osm_water" 
user = "admin"
password = ""

    [[providers.layers]]
    name = "water"
    geometry_fieldname = "geom"
    id_fieldname = "gid"
    sql = """
        SELECT 
            gid, ST_AsBinary(geom) AS geom 
        FROM 
            simplified_water_polygons 
        WHERE 
            geom && !BBOX!
    """

[[providers]]
name = "provider2"
type = "postgis"
host = "localhost"
port = 5432
database = "osm_sd" 
user = "foo"
password = ""

    [[providers.layers]]
    name = "water"
    geometry_fieldname = "way"
    id_fieldname = "osm_id"
    sql = """
        SELECT 
            osm_id, ST_AsBinary(way) AS way, name 
        FROM 
            planet_osm_polygon 
        WHERE 
            way && !BBOX! AND (waterway IS NOT NULL OR water IS NOT NULL)
    """

[[maps]]
name = "osm"

    [[maps.layers]]
    provider_layer = "provider1.water"
    min_zoom = 10
    max_zoom = 20

    [[maps.layers]]
    provider_layer = "provider2.water"
    min_zoom = 10
    max_zoom = 20
```
