### ISSUE TITLE
Multiple layers of the same name at different zooms

### ISSUE THREAD

**Issue by pnorman** [terranodo/tegola#87]
Is it possible to have two layers of the same name but non-overlapping zooms?

e.g.

```toml
[[maps]]
name = "foo"                             # used in the URL to reference this map (/maps/:map_name)

    [[maps.layers]]
    provider_layer = "osm.roads" # must match a data provider layer
    min_zoom = 10                           # minimum zoom level to include this layer
    max_zoom = 16                           # maximum zoom level to include this layer

    [[maps.layers]]
    provider_layer = "natural_earth.roads"  # must match a data provider layer
    min_zoom = 5                           # minimum zoom level to include this layer
    max_zoom = 9                           # maximum zoom level to include this layer
```

To achieve this effect, what is often done is

```sql

SELECT geom, 'motorway' as class, name, ... FROM natural_earth WHERE z(!scale!) <= 10
UNION ALL
SELECT geom, class, name, ... FROM osm_data WHERE z(!scale) > 10
```

But this can get to be painful to work with.
